[database]
name = "sdt_db_dev"
host = "localhost"
port = "27017"
username = "sdt_user_dev"
password =  "senha123"
collection = "Projetos"

[jaeger]
endpoint = "localhost:6831"

[application]
name = "api-sdt-dev"
