version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    networks:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mongodb
    volumes:
      - api-sdt-data:/data/mongodb
      - api-sdt-configdb:/data/configdb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sdt_user_prd
      MONGO_INITDB_ROOT_PASSWORD: senha123
      MONGO_INITDB_DATABASE: sdt_db_prd
  mongoexpress:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sdt_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha123
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    networks:
      - mongodb
  apisdt:
    image: apisdt-rust:local
    build:
      context: ../.
      dockerfile: ../api-sdt/build/deploy/Dockerfile
      network: host
    restart: always
    ports:
      - "8080:8080"
    environment:
      RUN_ENV: Production
    networks:
      - mongodb
    depends_on:
      - mongodb
networks:
  mongodb:
    driver: bridge
    ipam:
      config:
        - subnet: 172.34.0.0/16
volumes:
  api-sdt-data:
    external: true
  api-sdt-configdb:
    external: true
